steps:

  # Dockerize client
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'API_BASE_URL=$_API_BASE_URL',
      '-t', 'gcr.io/$PROJECT_ID/client:latest',
      '-f', 'dockerfiles/Dockerfile.client',
      '.'
    ]

  # Dockerize server
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/server:latest',
      '-f', 'dockerfiles/Dockerfile.server',
      '.'
    ]

  # Deploy client
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-client',
      '--image', 'gcr.io/$PROJECT_ID/client:latest',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '80',
      '--quiet',
      '--allow-unauthenticated']

  # Deploy server
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-server',
      '--image', 'gcr.io/$PROJECT_ID/server:latest',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '3000',
      '--quiet',
      '--allow-unauthenticated']

timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/client:latest'
  - 'gcr.io/$PROJECT_ID/server:latest'