steps:
  # Run tests
  - name: 'gcr.io/cloud-builders/docker'
    id: 'tests'
    args: [
      'build',
      '--build-arg', 'API_BASE_URL=$_API_BASE_URL',
      '-t', 'gcr.io/$PROJECT_ID/next-todo:test',
      '-f', 'dockerfiles/Dockerfile.test',
      '.'
    ]

  # Dockerize client
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['tests']
    args: [
      'build',
      '--build-arg', 'API_BASE_URL=$_API_BASE_URL',
      '-t', 'gcr.io/$PROJECT_ID/client:$SHORT_SHA',
      '-f', 'dockerfiles/Dockerfile.client',
      '.'
    ]

  # Dockerize server
  - name: 'gcr.io/cloud-builders/docker'
    waitFor: ['tests']
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/server:$SHORT_SHA',
      '-f', 'dockerfiles/Dockerfile.server',
      '.'
    ]

  # Push docker images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/client:$SHORT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/server:$SHORT_SHA']

  # Deploy client
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-client',
      '--image', 'gcr.io/$PROJECT_ID/client:$SHORT_SHA',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '80',
      '--quiet',
      '--allow-unauthenticated']

  # Deploy server
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-server',
      '--image', 'gcr.io/$PROJECT_ID/server:$SHORT_SHA',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '3000',
      '--quiet',
      '--allow-unauthenticated']

timeout: 1200s
images:
  - 'gcr.io/$PROJECT_ID/client:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/server:$SHORT_SHA'