steps:
  # Run the app and dependencies in the background using docker-compose.
  # Warning: this won't be cleaned up, which might be an issue if you run it
  # with the local builder.
  - name: 'docker'
    args: ['compose', 'up', '-d']
    env:
      - 'PROJECT_ID=$PROJECT_ID'

  # Deploy client
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-client',
      '--image', 'gcr.io/$PROJECT_ID/client:latest',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '80',
      '--quiet',
      '--allow-unauthenticated']

  # Deploy server
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run',
      'deploy', 'todo-server',
      '--image', 'gcr.io/$PROJECT_ID/server:latest',
      '--project', '$PROJECT_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--port', '3000',
      '--quiet',
      '--allow-unauthenticated']


images:
  - 'gcr.io/$PROJECT_ID/client:latest'
  - 'gcr.io/$PROJECT_ID/server:latest'