version: '3.8'
services:
  client:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.client
    container_name: client
    ports:
      - '80:80'

  server:
    build:
      context: ./
      dockerfile: dockerfiles/Dockerfile.server
    container_name: server
    ports:
      - '3000:3000'
    restart: 'unless-stopped'
