# ...........
# Test stage
# ...........
FROM node:14 as TEST_STAGE
WORKDIR /app
COPY . .

ARG API_BASE_URL

# Env vars available during build time
ENV VUE_APP_API_BASE_URL=$API_BASE_URL

RUN npm install --quite
RUN npm build
RUN npm run test:client
RUN npm run test:server