# ...........
# Build stage
# ...........
FROM node:lts-slim as BUILD_STAGE
WORKDIR /app
COPY . .
RUN npm install --quite
RUN npm run lint:client
RUN npm run test:client
RUN npm run build:client

# ................
# Production stage
# ................
FROM nginx:stable-alpine as PRODUCTION-STAGE
COPY --from=BUILD_STAGE /app/dist/client /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]