# ...........
# Build stage
# ...........
FROM node:14-slim as BUILD_STAGE
WORKDIR /app
COPY . .
RUN npm run build:server

# ................
# Production stage
# ................
FROM node:14 as PRODUCTION-STAGE
WORKDIR /app
COPY package*.json .
RUN npm install --production --quite
COPY --from=BUILD_STAGE /app/dist/server ./

EXPOSE 3000
ENV NODE_ENV production
CMD ["npm", "run", "start"]

